# Generated by Django 3.2.19 on 2023-08-17 15:01

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_scottishepcrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('page_name', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('data', models.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('feedback_download', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_download', to='portal.feedbackdownload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
