# Generated by Django 3.2.19 on 2024-01-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_scottishepcrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_id',
            field=models.IntegerField(default=0)
        ),
        migrations.RunSQL(
            sql="ALTER TABLE portal_referral DROP referral_id;",
            reverse_sql="ALTER TABLE portal_referral ADD referral_id INT DEFAULT 0;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE portal_referral ADD referral_id SERIAL;",
            reverse_sql="ALTER TABLE portal_referral DROP referral_id;"
        )

    ]
