# Generated by Django 3.2.19 on 2024-10-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_add_referral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scottishepcrating',
            name='address1',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='address2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='address3',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='alternative_improvements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='building_reference_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='built_form',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='co2_emissions',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='co2_emissions_per_floor_area',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='co2_emissions_potential',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='constituency',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='construction_age_band',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='current_energy_efficiency_rating',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='energy_consumption',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='energy_tariff',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='extension_count',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='floor_area',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='floor_description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='floor_energy_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='floor_height',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='floor_level',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='habitable_room_count',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='heated_room_count',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='improvements',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='inspection_date',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='lighting_description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='lighting_energy_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='lighting_environmental_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='local_authority',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='main_heating_description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='main_heating_energy_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='main_heating_environmental_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='main_heating_fuel_type',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='mains_gas',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='mechanical_ventilation',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='multiple_glazed_proportion',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='postcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='potential_energy_consumption',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='potential_energy_efficiency_rating',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='potential_rating',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='property_type',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='roof_description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='roof_energy_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='roof_environmental_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='second_heating_description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='second_heating_energy_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='tenure',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='wall_description',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='wall_energy_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='wall_environmental_efficiency',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='scottishepcrating',
            name='windows_description',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
