# Generated by Django 3.2.19 on 2023-12-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontdoor", "0008_auto_20230818_1451"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("access_token", models.CharField(max_length=65535)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
