# Generated by Django 5.1.8 on 2025-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontdoor", "0009_accesstoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("public_portal_open", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["created_at"],
                "abstract": False,
            },
        ),
    ]
