name: main_label_check

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - reopened
      - synchronize
      - unlabeled

jobs:
  label_check:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if no "production release" label is present while targeting main
        if: ${{github.event.pull_request.base.ref == 'main' && !contains(github.event.pull_request.labels.*.name, 'production release')}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed("Label is missing: add a 'production release' label in order to merge to main")
